Social_blog/blog/models.py
#models.py
from blog import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
      __tablename__= 'users'

      id =db.Column(db.Integer,primary_key=True)
      profile_image = db.Column(db.String(20),nullable=False,default='default_profile.png')
      email = db.Column(db.String(64),unique=True,index=True)
      username = db.Column(db.string,unique=True,index=True)
      password_hash = db.Column(db.String(128))

      posts = db.relationship('Blogpost', backref='author', lazy=True)


def __init__(self, email,username,password):
    self.email = email
    self.username = username
    self.password_hash = generate_password_hash(password)

def check_password(self,password):
    return check_password_hash(self.password_hash,password)

def __repr__(self):
    return f"Username{self.username}"



class Blogpost(db.Model):
    users = db.relationship(User)

    id = db.Column(db.Integer,primary_key=True)
    user_id = db.Column(db.Integer,db.ForiegnKey(users.id),nullable=False)

    date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    title = db.Column(db.String(140),nullable=False)
    text = db.Column(db.Text,nullable=False)

    def __init__(self,title,text,user_id):
        self.text = text
        self.title = title
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID:{self.id}--Date:{self.date}--{self.title}"



Social_blog/blog/__init__.py
#this is social blog/_init__.py

from flask import Flask
from blog.core.views import core
from blog.error_pages.handlers import error_pages
from flask_sqlalchemy import SQLAlchemy
import os
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)


########DATABASE SETUP#########

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False

db = SQLAlchemy(app)
Migrate(db,app)


###############################

#########LOGIN CONFIG#######

login_manager=LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'

app.register_blueprint(core)
app.register_blueprint(error_pages)

Social_blog/blog/core/views.py
#core/views.py
from flask import Flask

from flask import render_template, request, Blueprint

core = Blueprint('core',__name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

Social_blog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <meta charset="UTF-8">
    <title>PostBook</title>
</head>
<body>

<ul class="nav">
    <li class="nav-link">
        <a href = "{{url_for('core.index')}}">Home</a>
    </li>
    <li class="nav-link">
        <a href = "{{url_for('core.info')}}">About</a>
    </li>
    <li class="nav-link">
        <a href = "#">Log out</a>
    </li>
    <li class="nav-link">
        <a href = "#">Account</a>
    </li>
    <li class="nav-link">
        <a href = "#">Create Post</a>
    </li>
    <li class="nav-link">
        <a href = "#">Log in</a>
    </li>
    <li class="nav-link">
        <a href = "#">Register</a>
    </li>
</ul>

<div class="container">
    {%block content %}

    {% endblock %}

</div>

</body>
</html>

Social_blog/blog/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h1>Social Post</h1>
</div>

{%  endblock %}

Social_blog/blog/templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h1>Infor about Blog</h1>
  <p>bjkdbbddbwjkbjwbdjkbdjkwbd</p>
</div>

{%  endblock %}